In [1]:
import tensorflow as tf
import numpy as np
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.6.0


In [37]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [69]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Dense(2, activation= 'relu'),
  tf.keras.layers.Dense(2, activation= 'relu'),
  tf.keras.layers.Dense(2, activation= 'relu'),
  tf.keras.layers.Dense(2, activation= 'relu'),
  tf.keras.layers.Dense(2, activation= 'relu'),
  tf.keras.layers.Dense(1)
])

In [70]:
loss_fn = tf.keras.losses.MeanSquaredError()

In [71]:
model.compile(optimizer='adam',
              loss=loss_fn)

In [4]:
import numpy as np

x_random  = np.random.uniform(1, 100, 60000)

y_random =  tf.math.floor(x_random)  # np.array([int(str(x)[1]) for x in x_random ])
x_random , y_random

(array([63.06047642, 49.94477038, 81.71986124, ..., 81.00910599,
        16.53342225, 66.377158  ]),
 <tf.Tensor: shape=(60000,), dtype=float64, numpy=array([63., 49., 81., ..., 81., 16., 66.])>)

In [17]:
model.fit(x_random, y_random, epochs=10)

Epoch 1/10
1875/1875 [==============================] - 2s 898us/step - loss: 1433.2523
Epoch 2/10
1875/1875 [==============================] - 2s 971us/step - loss: 0.7591
Epoch 3/10
1875/1875 [==============================] - 2s 908us/step - loss: 0.6874
Epoch 4/10
1875/1875 [==============================] - 2s 904us/step - loss: 0.5578
Epoch 5/10
1875/1875 [==============================] - 2s 1ms/step - loss: 0.3698
Epoch 6/10
1875/1875 [==============================] - 2s 1ms/step - loss: 0.2315
Epoch 7/10
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1998
Epoch 8/10
1875/1875 [==============================] - 2s 981us/step - loss: 0.1981
Epoch 9/10
1875/1875 [==============================] - 2s 932us/step - loss: 0.1963
Epoch 10/10
1875/1875 [==============================] - 2s 971us/step - loss: 0.1946


In [21]:
input_array = np.array([[2.4]])
#input_array_for_prediction = np.expand_dims(input_array,axis=0)
input_array.tolist()
model(input_array).numpy()

array([[2.0527487]], dtype=float32)

In [37]:
l = tf.keras.layers.Dense(2, activation= tf.math.floor)

In [75]:
inp = np.array([3,3])
inp

array([3, 3])

In [76]:
l(inp)

ValueError: Input 0 of layer dense_25 is incompatible with the layer: : expected min_ndim=2, found ndim=1. Full shape received: (2,)